#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

// This is a placeholder for Nordic SDK configuration.
// In a real project, this file would be generated by the nRF Connect SDK
// or maintained manually based on the SDK's configuration system.
// It typically contains defines for enabling/disabling SDK modules, 
// configuring clock sources, peripheral settings, etc.

// Example: Enable NRFX_PRS (Peripheral Resource Sharing) if needed
#define NRFX_PRS_ENABLED 0

// Example: Configure NRF_LOG
#define NRF_LOG_ENABLED 0
#define NRF_LOG_DEFAULT_LEVEL 3

// Example: Enable NRFX GPIO driver
#define NRFX_GPIOTE_ENABLED 1

// Example: Enable NRFX UARTE driver
#define NRFX_UARTE_ENABLED 0

// Board specific configuration (usually included from boards.h or similar)
// For nRF52 DK, LED_1 is P0.17
#define LED_1 NRF_GPIO_PIN_MAP(0,17)

#endif // SDK_CONFIG_H
