#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

// This file is typically generated by the nRF Connect SDK or nRF5 SDK configuration tools.
// For a basic CMake setup, we provide a minimal version.

// <<< Use Configuration Wizard in Context Menu >>>

// <h> NRF_LOG - Logging
// ===========================================================
#ifndef NRF_LOG_ENABLED
#define NRF_LOG_ENABLED 0
#endif

#if NRF_LOG_ENABLED
// <o> NRF_LOG_DEFAULT_LEVEL  - Default severity level
// <0=> Off
// <1=> Error
// <2=> Warning
// <3=> Info
// <4=> Debug
#ifndef NRF_LOG_DEFAULT_LEVEL
#define NRF_LOG_DEFAULT_LEVEL 3
#endif

// <o> NRF_LOG_USES_COLORS  - If logging with colors is enabled.
// <0=> Off
// <1=> On
#ifndef NRF_LOG_USES_COLORS
#define NRF_LOG_USES_COLORS 0
#endif

#endif // NRF_LOG_ENABLED

// <h> CLOCK - Clock driver
// ===========================================================
#ifndef CLOCK_ENABLED
#define CLOCK_ENABLED 0
#endif

#if CLOCK_ENABLED
// <o> CLOCK_CONFIG_LF_SRC  - LF Clock Source
// <0=> RC
// <1=> XTAL
// <2=> Synth
#ifndef CLOCK_CONFIG_LF_SRC
#define CLOCK_CONFIG_LF_SRC 1
#endif
#endif // CLOCK_ENABLED

// <<< end of configuration section >>>

#endif // SDK_CONFIG_H
